version: "3"
services:
  prodottotest:
    image: prodotootest:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prodottotesst
    restart: always
    ports:
      - 8080:8080
    networks:
      - prodottotest

networks:
  prodottotest:
    external: true